paularmstrong/build-tracker

.flowconfig
flow-typed/build-tracker.js
flow-typed/npm/jest_v21.x.x.js
packages/app/package.json
packages/app/src/App.js
packages/app/src/api/normalization.js
packages/app/src/components/BuildInfo.js
packages/app/src/components/Chart.js
packages/app/src/components/ComparisonTable/ComparisonTable.js
packages/builds/.babelrc
packages/builds/README.md
packages/builds/jest.config.js
packages/builds/package.json
packages/builds/src/__tests__/meta.test.js
packages/builds/src/index.js
packages/builds/src/meta.js
packages/comparator/src/index.js
packages/server/package.json
packages/server/src/api/builds.js
packages/server/src/index.js

**Problem:** It would be beneficial to be able to provide links for keys in the build meta information
**Solution:** Add another package, `@build-tracker/builds` that includes utilities for working with builds. Currently only has methods for extracting meta information, but likely will add more to it.
Updated all references of `build.meta.<key>` to use the new methods available.

[builds] add package for working with and pulling data out of 'builds'

---

packages/app/src/components/ArtifactSwitch.js
packages/app/src/components/ComparisonTable/ComparisonTable.js
packages/app/src/components/ComparisonTable/RevisionHeaderCell.js
packages/app/src/components/ComparisonTable/ValueCell.js
packages/app/src/components/ComparisonTable/styles.js

*Problem:* No hovers on comparison table rows, hard to see what you're looking at
*Solution:* add hovers
*Problem:* ArtifactSwitch links were not encoded, so `i18n/en` breaks URLs when clicking
*Solution:* Use `encodeURIComponent`

[app] add table row hovers, fix artifact switch links

---

packages/app/package.json
packages/app/src/App.js
packages/app/src/ContextProvider.js
packages/app/src/api/index.js
packages/app/src/api/normalization.js
packages/app/src/components/BuildFilter/Modal.js
packages/app/src/components/BuildFilter/index.js
packages/app/src/components/BuildFilter/types.js
packages/app/src/components/BuildInfo.js
packages/app/src/components/Chart.js
packages/app/src/components/ComparisonTable/ComparisonTable.js
packages/app/src/modules/values.js
packages/builds/package.json
packages/builds/src/meta.js
packages/comparator/package.json
packages/comparator/src/index.js
packages/server/package.json
packages/server/src/api/builds.js
packages/server/src/index.js
packages/types/package.json
packages/types/src/index.js

**Problem:** Using global types in `./flow-typed/build-tracker.js` reduces the ability to properly check types in projects that depend on any of the build-tracker packages.
**Solution:** Add a new package, `@build-tracker/types` that exports these shared types.

[all] add packages/types

---

packages/comparator/src/__tests__/__snapshots__/index.test.js.snap
packages/comparator/src/__tests__/index.test.js
packages/comparator/src/index.js

**Problem:** The deltas and percent deltas were noticeably wrong.
**Solution:** Fix their calculation and ensure that the percentage in the default formatter uses a fixed number of decimals.
Mostly, the maps/reduces in `buildDeltas` and `getSum` were backwards in which was being sent as the `baseBuild` and which was the `changeBuild`. By fixing these orders, the deltas become correctly calculated

[comparator] fix delta & percent delta calculation

---

src/app/src/components/ColorScalePicker/__tests__/index.test.tsx
src/app/src/components/ColorScalePicker/index.tsx
src/app/src/components/ComparisonTable/ArtifactCell.tsx
src/app/src/components/ComparisonTable/ComparisonTable.tsx
src/app/src/components/ComparisonTable/DeltaCell.tsx
src/app/src/components/ComparisonTable/RevisionCell.tsx
src/app/src/components/ComparisonTable/RevisionDeltaCell.tsx
src/app/src/components/ComparisonTable/TextCell.tsx
src/app/src/components/ComparisonTable/TotalCell.tsx
src/app/src/components/ComparisonTable/TotalDeltaCell.tsx
src/app/src/components/ComparisonTable/__tests__/ArtifactCell.test.tsx
src/app/src/components/ComparisonTable/__tests__/ComparisonTable.test.tsx
src/app/src/components/ComparisonTable/__tests__/DeltaCell.test.tsx
src/app/src/components/ComparisonTable/__tests__/TextCell.test.tsx
src/app/src/components/ComparisonTable/__tests__/TotalCell.test.tsx
src/app/src/components/ComparisonTable/__tests__/TotalDeltaCell.test.tsx
src/app/src/components/Drawer.tsx
src/app/src/components/Graph/__tests__/index.test.tsx
src/app/src/components/Graph/index.tsx
src/app/src/screens/Main.tsx
src/app/src/screens/__tests__/Main.test.tsx

Toggling artifacts on and off causes re-render of every React component. This can make the UI lag >500ms
* Wrap all handlers/callbacks with [`useCallback`](https://reactjs.org/docs/hooks-reference.html#usecallback)
* Wrap cell components in `React.memo`
* This makes testing a bit of a pain.  Enzyme doesn't seem to play nice, so may consider an alternative test helping library
* Exported the non-memoized components and testing against those
* `shallow` on some higher-level components from memoized gets a bit funky. Had to disable a `Main` test.

Improve app performance with useCallback and memo

---

src/app/src/components/ColorScalePicker/ColorScale.tsx
src/app/src/components/Drawer.tsx
src/app/src/components/Graph/Area.tsx
src/app/src/components/Graph/__tests__/Area.test.tsx
src/app/src/components/SizeKeyPicker/SizeKeyButton.tsx
src/app/src/components/SizeKeyPicker/__tests__/SizeKeyButton.test.tsx
src/app/src/components/SizeKeyPicker/__tests__/index.test.tsx
src/app/src/components/SizeKeyPicker/index.tsx
src/app/src/screens/Main.tsx
src/comparator/src/__tests__/index.test.ts
src/comparator/src/index.ts

Unable to change the artifact size key used in the graph and table.
Fixes #29 
* Add `.sizeKeys` getter to comparator. Memoized and throws if some builds are missing keys (not sure if this is best long-term)
* Adds a sizeKeyPicker to the app drawer
* State managed by Main

Next size keys

---

config/postgres.js
demo/build-tracker.config.js
docs/docs/configuration.md
plugins/with-postgres/src/__tests__/queries.test.ts
plugins/with-postgres/src/__tests__/setup.test.ts
plugins/with-postgres/src/queries.ts
plugins/with-postgres/src/setup.ts
src/app/src/components/ComparisonTable/__tests__/ComparisonTable.test.tsx
src/app/src/components/Graph/__tests__/Area.test.tsx
src/app/src/components/Graph/__tests__/HoverOverlay.test.tsx
src/app/src/components/__tests__/BuildInfo.test.tsx
src/app/src/store/__tests__/reducer.test.ts
src/app/src/views/__tests__/Graph.test.tsx
src/build/src/index.ts
src/cli/src/commands/__tests__/create-build.test.ts
src/cli/src/commands/create-build.ts
src/cli/src/modules/__tests__/git.test.ts
src/cli/src/modules/git.ts
src/comparator/src/__tests__/BuildDelta.test.ts
src/comparator/src/__tests__/index.test.ts
src/server/src/api/__tests__/insert.test.ts
src/server/src/api/__tests__/read.test.ts
src/server/src/api/index.ts
src/server/src/api/insert.ts
src/server/src/api/read.ts
src/server/src/server.ts
src/server/src/types.ts

One of the main use-cases with Build Tracker is to catch issues with branches before they're merged to your production branch.
Add support to insert, read, compare, and visualize changes from the merge-base and any arbitrary build on different branches, but still keep those non-production branch builds separate from the main UI.

Branch support

---

config/mariadb.js
docs/docs/plugins/index.md
docs/docs/plugins/with-mariadb.md
docs/docs/plugins/with-postgres.md
docs/website/sidebars.json
package.json
plugins/with-mariadb/README.md
plugins/with-mariadb/jest.config.js
plugins/with-mariadb/package.json
plugins/with-mariadb/src/__tests__/index.test.ts
plugins/with-mariadb/src/__tests__/queries.test.ts
plugins/with-mariadb/src/__tests__/setup.test.ts
plugins/with-mariadb/src/index.ts
plugins/with-mariadb/src/queries.ts
plugins/with-mariadb/src/setup.ts
plugins/with-mariadb/tsconfig.json
src/server/src/commands/seed.ts
yarn.lock

For those that use MySQL/MariaDB flavors, it would be great to provide an out-of-the-box plugin
Went with MariaDB as it seems like the more acceptable open-source flavor now. Mostly lifted from the Postgres plugin, but required a few changes. Most notably, the return values are arrays and not objects with keys of information. Blobs from the DB turn into Buffers in JS, so they need extra parsing before being returned.
Also added a couple dev modes: `yarn dev:maria` and `yarn dev:postgres`, as well as a `seed` command for the server that will drop in data from the fixtures package.

Add @build-tracker/plugin-with-mariadb

---

docs/website/core/Footer.js

The website footer has two broken links: plugins and guides. This fixes plugins. I don't know how Guides should be handled, since I found no guide(s) in the nearby folders.

[docs] fix broken link

---

docs/website/blog/2019-03-22-version-1.md

The 1.0.0 blog post is lacking anything useful
Convert it to an announcement/roadmap information post
Fixes #61

[blog] update 1.0.0 blog post as roadmap

---

src/cli/package.json

I couldn't install `@build-tracker/cli` using NPM due to the following error:
```
ENOENT: no such file or directory, chmod '/Users/.../node_modules/@build-tracker/cli/dist/bin'
This is related to npm not being able to find a file.
```
After small investigation it figure out that the problem was with `bin` path in package.json.
According to [NPM documentation](https://docs.npmjs.com/files/package.json#bin) it's better to use relative path with file extension.

fix(@build-tracker/cli): Use relative path for bin script

---

src/server/src/index.ts

We were running into an error with the environment with the uppercase `#!/usr/bin/env Node`:
```
bt-server_1  | /usr/bin/env: 'Node': No such file or directory
bt-server_1  | error Command failed with exit code 127.
```
I believe changing this to `#!/usr/bin/env node` will fix this on all environments.

fix(bt-server): fix PATH reference to Node.js

---

plugins/with-mariadb/package.json
plugins/with-postgres/package.json
src/comparator/package.json
src/formatting/package.json
src/server/package.json

yarn v2 requires all dependencies to be explicitly declared in `dependencies` of `package.json`. Otherwise it fails with e.g.
```bash
Error: A package is trying to access another package without the second one being listed as a dependency of the first one
Required package: @build-tracker/build (via "@build-tracker/build")
Required by: @build-tracker/plugin-with-postgres@npm:1.0.0-alpha.3 
```
Even with 1.x you get missing module errors for `@build-tracker/types` and `glob`
Added any dependency that got reported when running `yarn bt-server run`.
- ~[ ] 📖 Update relevant documentation~

chore(package): Add implicit dependencies to `dependencies`

---

.github/workflows/pull_request.yml
.github/workflows/push.yml

The actions, especially for PRs are not explicitly bucketed into jobs.
Bucket them logically so they hopefully run faster and are easy to follow

[chore] split up PR and Push actions

---

.github/workflows/push.yml
docs/docs/app.md
docs/docs/cli.md
src/api-errors/src/index.ts
src/cli/src/commands/__tests__/upload-build.test.ts
src/cli/src/commands/upload-build.ts
src/server/src/api/__tests__/protected.test.ts
src/server/src/api/index.ts
src/server/src/api/protected.ts

The `/api/build` POST endpoint is totally open and anyone can write to it.
If an env variable, `BT_API_AUTH_TOKEN` is set, it will be used to protect all POST requests to the API.

[api] add BT_AUTH_API_TOKEN env var to protect POST endpoint

---

config/mysql.js
docs/docs/guides/development.md
docs/docs/plugins/index.md
docs/docs/plugins/with-mysql.md
docs/website/sidebars.json
package.json
plugins/with-mariadb/README.md
plugins/with-mysql/README.md
plugins/with-mysql/jest.config.js
plugins/with-mysql/package.json
plugins/with-mysql/src/__tests__/index.test.ts
plugins/with-mysql/src/__tests__/queries.test.ts
plugins/with-mysql/src/__tests__/setup.test.ts
plugins/with-mysql/src/index.ts
plugins/with-mysql/src/queries.ts
plugins/with-mysql/src/setup.ts
plugins/with-mysql/tsconfig.json
yarn.lock

While the MariaDB plugin _may_ work with MySQL databases, it's potential that it won't always work. Probably better to create an official plugin now so it's easier to maintain later.
Mostly copypasta from `with-mariadb`, but uses the `mysql` package from NPM, which does not use promises, so I had to get into callbacks.

[feature] Add plugin with-mysql

---

docs/docs/cli.md
docs/docs/guides/ci.md
src/server/src/api/__tests__/insert.test.ts
src/server/src/api/insert.ts

When inserting with the API or CLI, it's difficult to scrape out usable information about budgets failing or passing.
In the response from the API insert method, add two items, `groupDeltas` and `artifactDeltas`, extracted from the `buildDelta` between the build and its parent.

[server] return budget results in the insert response

---

src/app/src/client/index.tsx
src/app/src/components/Graph/HoverOverlay.tsx
src/app/src/components/Graph/StackedBar.tsx
src/app/src/components/Graph/__tests__/StackedBar.test.tsx
src/app/src/components/Graph/__tests__/index.test.tsx
src/app/src/components/Graph/index.tsx
src/app/src/icons/BarChart.tsx
src/app/src/icons/LineChart.tsx
src/app/src/store/__tests__/reducer.test.ts
src/app/src/store/actions.ts
src/app/src/store/index.ts
src/app/src/store/reducer.ts
src/app/src/store/types.ts
src/app/src/views/AppBar.tsx
src/app/src/views/Drawer.tsx
src/app/src/views/__tests__/AppBar.test.tsx

Viewing area charts for small numbers of revisions makes it difficult to discern differences
Add a _Stacked Bar_ graph option.
* Persists when copying links
* Defaults to stacked view when receiving 10 or fewer builds
* Can be toggled via the _Drawer_
Fixes #91

[app] add stacked bar chart option

---

src/comparator/src/__tests__/index.test.ts
src/comparator/src/index.ts
src/formatting/src/__tests__/index.test.ts
src/formatting/src/index.ts

Big tables of data are not always preferred from the comparator output, especially when you have a bunch of budgets set. The tables could provide too much noise and not get enough attention over time.
Add a `toSummary()` method to the `Comparator` that outputs an array of strings for each failing budget — or a success message.

Add summary output option to comparator

---

src/cli/src/modules/__tests__/config.test.ts
src/cli/src/modules/config.ts
src/fixtures/cli-configs/rc/.build-trackerrc-invalid.js

Currently, if the config file errors, the CLI will return a generic error message: "Could not find configuration file". However this is misleading, because the config _was_ found.
With this PR, we only use this error message when the config file was genuinely not found. Otherwise we use the error that came from the config file.

Fix config error

---

src/cli/src/commands/__tests__/upload-build.test.ts
src/cli/src/commands/upload-build.ts
src/cli/src/modules/config.ts
src/fixtures/cli-configs/rc/.build-trackerrc.js

The value of `response` that's passed into `onCompare` does not match the param type (`ApiReturn`).
```sh-session
$ node
> Buffer.from(['{"success":"yep"}']).toJSON()
{ type: 'Buffer', data: [ 0 ] }
```
I had to make this change to get it working.
I don't understand how the tests are passing?

Fix upload build response

---

src/app/src/components/ComparisonTable/ArtifactCell.tsx

Artifact names in the comparison table can end up really long, causing too much space to be used by the ArtifactCell column of the table.
* Truncate to max 15vw with an ellipsis.
* Adds a tooltip that explains what happens when clicked, as well as the full name.

[app] Add ellipsis to long ArtifactCells

---

src/cli/package.json
src/server/package.json
yarn.lock

Jest upgrade caused builds to fail because of multiple `@types/yargs` versions. 
Upgrade yargs to latest (matches jest). Not sure how to make a better long-term solution in which these can deviate

[chore] upgrade yargs (fixes builds)

---

.github/workflows/pull_request.yml
.github/workflows/push.yml

Speed of github actions is fairly dependent on pulling dependencies
Use `actions/cache`. Copypasta from [docs](https://github.com/actions/cache/blob/master/examples.md#node---yarn)

[chore] add cache to github actions

---

.github/workflows/pull_request.yml

A commit broke builds but didn't know until it was merged to master
Ensure `yarn build` is run on PRs

[chore] ensure Build task is run on PRs

---

src/server/src/api/insert.ts

Without this, the top level `budgets` config doesn't seem to do anything.
Note: I wasn't sure how to write a test for this one?

Pass budgets through to `Comparator`

---

src/server/src/__tests__/server.test.ts
src/server/src/server.ts

If an `artifacts` config is not provided, or the optional parts are missing, the application can silently fail.
Default all keys and assign the provided config over the default.
Fixes #104

[server] default artifactConfig parts individually (#104)

---

docs/docs/packages/server.md
src/app/src/store/__tests__/reducer.test.ts
src/app/src/store/reducer.ts
src/app/src/store/types.ts
src/server/src/server.ts
src/types/src/index.ts

Re. https://github.com/paularmstrong/build-tracker/issues/14#issuecomment-587124783

Add `defaultSizeKey`

---

docs/docs/guides/ci.md

Forgot to update this example alongside my fixes in https://github.com/paularmstrong/build-tracker/pull/131. The _current_ build will now be the last item in the array, not the first.

Correct CI example

---

src/app/src/components/Graph/XAxis.tsx
src/app/src/components/Graph/__tests__/XAxis.test.tsx

Too many builds on the graph can overlap labels
* Set a maximum number of tick labels to 50 (hard-coded)
* Evenly set tick labels to empty string if there are more than 50 builds in the x-axis domain

[app] limit number of tick labels to prevent overlap

---

src/app/src/store/__tests__/reducer.test.ts
src/app/src/store/index.ts
src/app/src/store/reducer.ts
src/app/src/store/types.ts
src/server/src/server.ts

The sum budgets (main key `budgets` in server config) are not passed into the app
Add them. Ensure they are passed into the `comparator` and `activeComparator`

[app][server] ensure budgets passed to comparator

---

src/formatting/src/__tests__/index.test.ts
src/formatting/src/index.ts

Reading percent deltas like `10.000%` is silly
Since this is for visual inspection and actual values tend to be more important if you want to run real reports, simply do a ceiling at 1 decimal place.

[formatting] reduce zeroes in %-value formatting

---

src/app/src/icons/ListBulleted.tsx
src/app/src/views/AppBar.tsx
src/app/src/views/__tests__/AppBar.test.tsx

Summaries are nice. Can't get them from the UI
Add `Copy summary` from the AppBar dropdown

[app] add copy as summary to appbar dropdown

---

src/app/src/views/AppBar.tsx
src/app/src/views/__tests__/AppBar.test.tsx

When I share links with people, I expect the graph to be limited to the selected revisions only. Currently, it relies on the query that is run, which may be invalid long-term. Example: get 10 most recent builds and share a link to the first two–as soon as two new builds are made, this URL will not work.
Always give a URL with a path directly to the builds.

[app] copy link limits to selected revisions

---

src/app/src/components/BuildInfo.tsx
src/app/src/components/__tests__/BuildInfo.test.tsx
src/cli/src/commands/__tests__/create-build.test.ts
src/cli/src/commands/create-build.ts

All meta values on builds can be linkable, but this isn't reflected in the `BuildInfo` panel.
Ensure they're all linked if a URL is available.

[app] ensure all meta items in BuildInfo are linked if URL is available

---

src/comparator/src/__tests__/index.test.ts
src/comparator/src/index.ts

Sometimes in the UI, my builds appear out of order when I link directly to a comparison, because the SHAs get alpha-numeric sorted.
The comparator can automatically sort the builds.
* First, by timestamp
* Second, by checking revision/parentRevision and determining if one should come directly after the other
Related: 
* 81d47870a40477de4bc42d63df782b4a8f74689b
* #130 
* #131

[comparator] sort builds on comparator create

---

src/cli/src/commands/__tests__/create-build.test.ts
src/cli/src/commands/__tests__/stat-artifacts.test.ts
src/cli/src/commands/stat-artifacts.ts
src/fixtures/cli-configs/fakedist/test-folder/test-no-extension
src/fixtures/cli-configs/rc/.build-trackerrc.js

We tried to use the glob `**/*` to include all artifacts, regardless of file extension, however we were getting an exception:
```
EISDIR: illegal operation on a directory, read
```

Ignore directions when running glob

---

docs/docs/packages/api-errors.md
src/api-errors/src/index.ts
src/server/src/api/__tests__/insert.test.ts
src/server/src/api/insert.ts

There's no validation on `insert` of a build using the API.
Add remedial validation to the two most important fields, `revision` and `timestamp`
fixes #25

[server] add api insert validation

---

docs/docs/packages/comparator.md
src/app/src/components/ComparisonTable/DeltaCell.tsx
src/app/src/components/ComparisonTable/__tests__/DeltaCell.test.tsx
src/app/src/icons/Hash.tsx
src/comparator/src/__tests__/index.test.ts
src/comparator/src/index.ts
src/formatting/src/__tests__/index.test.ts
src/formatting/src/index.ts

* Unexpected hash changes are not denoted in markdown tables
* They share the same icon in the UI as regular budget warnings
Fixes #151
* Unify the "error" emoji to 🚨
* Use #️⃣ for unexpected hash changes in markdown table and summaries
* Add an icon the looks like #️⃣ to the app UI, use that instead of warning icon

Unify emoji

---

docs/docs/packages/cli.md
src/cli/src/commands/__tests__/create-build.test.ts
src/cli/src/commands/create-build.ts
src/cli/src/commands/upload-build.ts

Build Meta can accept any arbitrary data and display it in the UI, assuming it matches the format `{ [key: string]: string | { url: string, value: string } }`. Unfortunately, the CLI does not have any way to set this information.
* Adds a `--meta` option that takes a string of JSON-encoded, parses it, and attaches it to the Build.
* Unifies the arguments that are shared between `create-build` and `upload-build`
Fixes #150

[cli] add --meta option for passing extra data into a build

---

src/app/src/components/ComparisonTable/ArtifactCell.tsx
src/app/src/components/ComparisonTable/DeltaCell.tsx
src/app/src/components/ComparisonTable/GroupCell.tsx
src/app/src/components/ComparisonTable/RevisionDeltaCell.tsx
src/app/src/components/Graph/HoverOverlay.tsx
src/app/src/components/RelativeTooltip.tsx
src/app/src/components/Tooltip.tsx
src/app/src/components/__tests__/RelativeTooltip.test.tsx
src/app/src/components/__tests__/Tooltip.test.tsx

There's no information while hovering over the graph in the app that can help verify what build/revision you're about to interact with.
* Refactor `Tooltip` into `Tooltip` (`left`, `top` props) and `RelativeTooltip` (`relativeTo` prop)
* Use `RelativeTooltip` where `Tooltip` was used before
* Use `Tooltip` in `HoverOverlay` to show revision value and current hovered artifact
Fixes #12

[app] add tooltips to graph when hovering

---

docs/docs/guides/guides.md
docs/docs/guides/heroku.md
docs/sidebars.js

There are no easy "getting started" docs for deploying the server to a free service
Created a github template: [paularmstrong/build-tracker-heroku](https://github.com/paularmstrong/build-tracker-heroku)
Added docs with instructions
Fixes #66

[docs] add instructions for deploying to heroku

---

plugins/with-mariadb/README.md
plugins/with-mysql/README.md
plugins/with-postgres/README.md
src/api-client/README.md
src/api-errors/README.md
src/app/README.md
src/build/README.md
src/cli/README.md
src/comparator/README.md
src/fixtures/README.md
src/formatting/README.md
src/server/README.md
src/types/README.md

There are no README files in published versions, which is not great when looking on yarnpkg.com or npmjs.com
I don't really want to keep every README up to date with docs as well as the actual docs site. For now, just giving a short description and pointing to the buildtracker.dev site.

[chore] add README files that point to the docs

---

plugins/with-mariadb/package.json
plugins/with-mysql/package.json
plugins/with-postgres/package.json
src/api-client/package.json
src/api-errors/package.json
src/app/config/webpack-client.config.js
src/app/config/webpack-server.config.js
src/app/tsconfig.json
src/build/package.json
src/cli/package.json
src/comparator/package.json
src/fixtures/index.js
src/fixtures/package.json
src/formatting/package.json
src/server/package.json
src/types/package.json
tsconfig.json

(From #105, per @OliverJAsh )
The `types` field in the `package.json` of `@build-tracker/plugin-with-postgres` currently refers to the TS _source code_:
https://github.com/paularmstrong/build-tracker/blob/f66274bba0003e58cd2922b759cc883222e21ac9/plugins/with-postgres/package.json#L10
This means that TS users who import from this module will get lots of errors relating to the source code.
It would be better if the `types` field instead just referred to some declaration files (`.d.ts`). These could be generated using the `declaration` compiler option. This way, users will only import the types—they won't be forced to type check the actual source code itself.
Using `declarations: true` in the root `tsconfig.json` seems to ensure the declaration files are built, but references in the monorepo …

[fix] Export TS declaration files

---

.github/workflows/pull_request.yml
codecov.yml

Code coverage helps ensure fewer regressions in behavior.
Add codecov

[chore] add codecov to pushes

---

src/app/src/components/Graph/__tests__/index.test.tsx
src/app/src/components/Graph/index.tsx

When using the Area style graph and a lot of builds, too much horizontal space can be given at the edges of the graph:
Removing the `round`ing from the `xScale` prevents D3 from wonky calculations.

fix(app): prevent extra horizontal padding on area graph

---

src/api-client/src/modules/__tests__/upload-build.test.ts
src/api-client/src/modules/config.ts
src/server/src/api/insert.ts

The example at https://buildtracker.dev/docs/guides/advanced-ci/ fails to type check, because the `onCompare` parameter (`ApiReturn`) seems to be incorrect.

Correct `ApiReturn` type

---

src/cli/src/bin.ts
src/server/src/index.ts

When running `bt-cli upload-build`, I was getting this error:
```
/Users/oliverash/Development/unsplash-web/node_modules/@build-tracker/cli/dist/commands/create-build.d.ts:4
import { Argv } from 'yargs';
^
SyntaxError: Unexpected token {
at Module._compile (internal/modules/cjs/loader.js:811:22)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
at Module.load (internal/modules/cjs/loader.js:731:32)
at Function.Module._load (internal/modules/cjs/loader.js:644:12)
at Module.require (internal/modules/cjs/loader.js:771:19)
at Object.require (internal/modules/cjs/helpers.js:68:18)
at /Users/oliverash/Development/unsplash-web/node_modules/require-directory/index.js:76:17
at Array.forEach (<anonymous>)
at requireDirectory …
```

Exclude TS declaration files from yargs require

---

docs/docs/installation.md

two problems. 
one was a 404 of docs. easy.
other is was that i first tried `applicationUrl: 'https://lh-build-tracker.herokuapp.com/',`. It turns out that trailing slash leads to some unexpected results, where the "API" returns HTML and it all goes haywire. :)  I added a small console.log on the API response to see what was happening. Anyway, the fix seemed to be dropping the trailing slash.    I figure leaving it out here may help future users.  Up to you if you want a different fix :)

docs: Fix CLI docs link & specific applicationUrl

---

docs/docs/packages/comparator.md
src/app/src/components/ComparisonTable/__tests__/DeltaCell.test.tsx
src/comparator/src/__tests__/index.test.ts
src/comparator/src/index.ts
src/formatting/src/__tests__/index.test.ts
src/formatting/src/index.ts

When outputting markdown tables from the comparator `toMarkdown` function, when artifact names have more than one tilde (~) in them, it strikes through some of the text.
For example:
I expect `foo~bar~baz` to have two tildes, but instead, it looks like this:
foo~bar~baz
For now, just escape those single characters both in `toMarkdown()` as well as `toSummary()`
fixes #179

fix(comparator): ensure artifact names have tildes escaped for markdown

---

docs/docs/installation.md

What you had didn't work for me. I imagine you split out the CLI package later on?
:)

docs: install the CLI not API client

---

src/app/src/components/ComparisonTable/DeltaCell.tsx
src/app/src/components/ComparisonTable/__tests__/BodyRow.test.tsx
src/app/src/components/ComparisonTable/__tests__/DeltaCell.test.tsx
src/app/src/components/ComparisonTable/__tests__/GroupRow.test.tsx
src/comparator/src/ArtifactDelta.ts
src/comparator/src/__tests__/ArtifactDelta.test.ts
src/comparator/src/__tests__/index.test.ts
src/comparator/src/index.ts

There is a discrepency between when the _unexpected hash change_ icon #️⃣is shown in markdown (from comparator) vs the web UI.
The web UI had different logic in that it showed the icon if-and-only-if the _current_ size delta is 0, but not if one of the other size keys had a delta. for example, it would show if the gzip size is unchanged, but the stat size has changed. This is incorrect, because we would actually expect the hash to change in that case.
This adds a getter to the `ArtifactDelta` object as a source of truth to know if the hash change was unexpected. This removes the need for duplicative logic in a few places.
Fixes #178

fix(comparator): ensure hash change only shows when all sizes unchanged

---

src/api-client/src/modules/__tests__/upload-build.test.ts
src/api-client/src/modules/upload-build.ts
src/cli/src/commands/upload-build.ts
src/server/src/api/protected.ts

Errors from the api-client and cli are pretty vague. They do not indicate what went wrong and how to fix it.
Include more context in the response for `AuthError`s. Update the api-client to properly log the error response string instead of `[object Object]`
Example: <img width="1023" alt="Screen Shot 2020-03-20 at 9 06 46 AM" src="https://user-images.githubusercontent.com/33297/77183032-f49a3780-6a8a-11ea-86af-5254fee7d2cf.png">
Fixes #176 
Fixes #177
cc @paulirish

fix(api): ensure output from api/api-client gives context

---

docs/docs/guides/contributing.md

Contributing docs for the docs were referencing docusaurus v1, but we switched to v2.
Update docs for v2 compatibility

docs: update contributing docs for docusaurus v2

---

tsconfig.test.json

The CI/test config for typescript is missing excludes for `dist` directories in the `plugins` workspaces
Add the excludes

ci: update ci tsc config excludes

---

src/app/src/components/BuildInfo.tsx
src/app/src/components/ComparisonTable/DeltaCell.tsx
src/app/src/components/ComparisonTable/TotalCell.tsx
src/app/src/components/ComparisonTable/__tests__/DeltaCell.test.tsx
src/app/src/components/ComparisonTable/__tests__/TotalCell.test.tsx
src/app/src/components/RelativeModal.tsx
src/app/src/components/TabularMetadata.tsx
src/app/src/components/__tests__/BuildInfo.test.tsx
src/app/src/components/__tests__/TabularMetadata.test.tsx
typings/react-native/index.d.ts

Sometimes when I'm digging into the table, I want to see more information about the artifact in the build or the delta (like all sizeKey changes, etc). There's currently no short way of doing that.
On press (click), a modal window could open that nicely formats the full `Artifact` or `ArtifactDelta` object (depending on which cell type).
Closes #183

feat(app): add modal dialogs to comparison table

---

README.md

docs: fix readme typo in url

---

src/api-client/src/modules/spawn.ts

Sometimes buildtracker fails randomly. Example: https://github.com/GoogleChrome/lighthouse/runs/1130093961?check_suite_focus=true#step:19:25
since we have no idea what command triggered a nonzero exit code, it's a bit hard to debug.
since the error object that spawn() rejects with already has a few things, and is logged out to stderr... i figure why not.
fixes #200

chore(api-client): add child process invocation command to error output

---

plugins/with-mariadb/src/__tests__/setup.test.ts
plugins/with-mariadb/src/setup.ts
plugins/with-mysql/src/__tests__/setup.test.ts
plugins/with-mysql/src/setup.ts
plugins/with-postgres/src/__tests__/setup.test.ts
plugins/with-postgres/src/setup.ts
src/server/src/commands/seed.ts

Some people use really long git branch names, sometimes automated systems do that. We currently limit branch names in the official database plugins to 64 characters.
Increase to 256 characters.
Fixes #205 
Ideally in a longer term solution, we should include schema versions in the database to know what migrations need to be run. This is something we could investigate as a larger epic.

fix: increase branch name length to 256-char

---

.github/workflows/pull_request.yml
.github/workflows/push.yml
src/cli/src/commands/__tests__/create-build.test.ts
src/comparator/src/BuildDelta.ts
src/comparator/src/__tests__/BuildDelta.test.ts
src/comparator/src/__tests__/index.test.ts
src/comparator/src/index.ts

Switching from Node 10 to Node 12 produces an issue that suddenly `brotli` will be included in available `sizeKeys` for builds. This causes various things to throw errors because they're hardcoded to not allow a change in the `sizeKeys`
This manual throwing seems unnecessary. By removing these checks, we can allow comparisons with the given keys, the result will just cause the comparison to show `0`s for the build missing that size key.
Also updated CI to node 12

feat(comparator cli): allow comparisons even if size keys do not match

---

src/api-client/package.json
src/api-client/src/modules/config.ts
yarn.lock

`cosmiconfig` is 2 major versions out-of-date.
Update `cosmiconfig` to `^7.0.0`. `cosmiconfig` is now written in TypeScript so `@types/cosmiconfig` is no longer necessary; `cosmiconfig` is also now a named export rather than the default export.

chore: Upgrade cosmiconfig to ^7.0.0
